spring:
  application:
    name: optica

  datasource:
    url: jdbc:mysql://localhost:3306/optica?useSSL=false&serverTimezone=America/Lima&allowPublicKeyRetrieval=true
    username: admin_optica
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
