import {
  IconDashboard,
  IconClientes,
  IconEmpleados,
  IconPerfiles,
  IconInventario,
  IconVentas,
  IconCompras,
  IconReportes,
  IconGestionWeb,
  IconConfig,
  IconMarcas,
  IconCategorias,
  IconUnidades,
} from "../components/ui/IconCatalog";

export const iconMap = {
  IconDashboard: <IconDashboard />,
  IconClientes: <IconClientes />,
  IconEmpleados: <IconEmpleados />,
  IconPerfiles: <IconPerfiles />,
  IconInventario: <IconInventario />,
  IconVentas: <IconVentas />,
  IconCompras: <IconCompras />,
  IconReportes: <IconReportes />,
  IconGestionWeb: <IconGestionWeb />,
  IconConfig: <IconConfig />,
  IconMarcas: <IconMarcas />,
  IconCategorias: <IconCategorias />,
  IconUnidades: <IconUnidades />,
};
